### ISSUE TITLE
Drop PR title validation

### ISSUE THREAD

**Issue by PhilinTv** [oryx-frontend/oryx#32]
While at some teams prefixes like "chore" to commits and PRs are a daily business, they create problems for newbie contirbutors.
And while they create additional challenges, their value is not that high.

WDYT, about removing additional commit and PR title validations?

**Comment by tolerants** [comment]
Right now it specify release/feature type. So it will be much more difficult to understand what type of release we have, how to generate change logs and so on. So I assume I’ll be a releaser of Oryx, and in case we drop it - it will make my life more difficult, I’ll need to adjust some scripts and also analyze every merged PR separetly before release.

So I strongly do not recommend it for now. Maybe we can think about automation for it, but as long as we don't have public API really specified it looks like a big feature.

**Comment by PhilinTv** [comment]
@tolerants if you are afraid of complex release process, maybe we can just use Github labels for marking Features/Bug/Enhancement in PRs? Then we can still drop this not-friedly automation.

**Comment by tolerants** [comment]
@PhilinTv But we are not able to get github labels in git. So again in this case we have to check all the PR's manually or create a small script to gather this information (maybe there is a github action for it). 

Maybe we can at least put a small explanation into PR template regarding conventional commits so it will slightly improve an experience for contributors?

**Comment by PhilinTv** [comment]
@tolerants even at this simple doc case there are plenty of nuances :)
https://github.com/oryx-frontend/oryx/pull/34#issuecomment-2165432871


>But we are not able to get github labels in git.

Why do you need this information in Git? We would typically write BC-breaks in the GH release notes.
Do you need them somewhere else?

PS. Somehow these guys manage it without "chore" schema 😄 
https://github.com/vercel/next.js/pulls

**Comment by tolerants** [comment]
@PhilinTv Vercel is having different release process. Like every other library.
I'm just describing how our release process is working right now. Let's have a sync on it and decide if we can adjust/simplify it for easier contribution and at the same time it shouldn't be painful to release.

**Comment by PhilinTv** [comment]
WE Removed title validation for now.
