### ISSUE TITLE
Formatter CI only works with the root repo

### ISSUE THREAD

**Issue by PhilinTv** [oryx-frontend/oryx#35]
Here the CI is failing due to the PR coming from the fork.
https://github.com/oryx-frontend/oryx/pull/30

![debug1](https://github.com/oryx-frontend/oryx/assets/376033/be1984d0-7345-40ea-aaf7-bdc61b77da23)

**Comment by tolerants** [comment]
Fixed with https://github.com/oryx-frontend/oryx/pull/38
